baseURL = "https://aws-sensei.cloud/"
theme = "LoveIt"

title = "AWS Sensei"

languageCode = 'en'
defaultContentLanguage = "en"
languageName = "English"

enableEmoji = true

[pagination]
  disableAliases = false 
  pagerSize = 10
  path = "page"
  
[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
      [[languages.en.menu.main]]
        weight = 2
        identifier = "about"
        name = "About"
        url = "/about/"
      [[languages.en.menu.main]]
        weight = 3
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
      [[languages.en.menu.main]]
        weight = 4
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        url = "https://github.com/AWS-Sensei"
        title = "GitHub"
    [languages.en.params.home]
      [languages.en.params.home.profile]
        title = "Tech Lead and AWS Developer"
        subtitle = "This blog is a place for me to share what I’ve learned, capture my thoughts, and hopefully help others along the way."
  [languages.de]
    weight = 1
    languageCode = "de"
    languageName = "Deutsch"
    hasCJKLanguage = false
    [languages.de.menu]
      [[languages.de.menu.main]]
        weight = 1
        identifier = "posts"
        name = "Beiträge"
        url = "/posts/"
      [[languages.de.menu.main]]
        weight = 2
        identifier = "about"
        name = "Über mich"
        url = "/about/"
      [[languages.de.menu.main]]
        weight = 3
        identifier = "projects"
        name = "Projekte"
        url = "/projects/"
      [[languages.de.menu.main]]
        weight = 4
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        url = "https://github.com/AWS-Sensei"
        title = "GitHub"
    [languages.de.params.home]
      [languages.de.params.home.profile]
        title = "Tech Lead und AWS Developer"
        subtitle = "Mit diesem Blog möchte ich mein Wissen teilen, Gedanken festhalten und vielleicht auch anderen Entwickler:innen auf ihrem Weg weiterhelfen."



[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/AWS-Sensei/Blog"
  dateFormat = "2006-01-02"
#  title = "Marcel Baltzer"
#  description = "Marcel Baltzer's Blog"

[params.header]
  [params.header.title]
    name="AWS Sensei"

[params.footer]
  enable = false

[params.section]
  paginate = 20
  dateFormat = "01-02"
  rss = 10

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    avatarURL = "/images/avatar.png"
#    title = "Tech Lead and AWS Developer"
#    subtitle = "This blog is a place for me to share what I’ve learned, capture my thoughts, and hopefully help others along the way."
    typeit = true
    social = true
    [params.home.posts]
      enable = true
      paginate = 3

[params.social]
  GitHub = "Marcel-Baltzer"
  Linkedin = "marcel-baltzer-4a369a93"
  Xing = "Marcel_Baltzer"
  Email = "marcel.baltzer@hotmail.de"
  RSS = true

[params.page]
  [params.page.share]
    enable = false
  [params.page.code]
   copy = true
  [params.page.comment]
   enable = true



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.cognitoDrafts]
  enable = true
  domain = "YOUR_DOMAIN"
  clientId = "YOUR_CLIENT_ID"
  redirectUri = "https://aws-sensei.cloud/"
  logoutUri = "https://aws-sensei.cloud/"
  scope = "openid email profile"

[params.library]
  js = ["js/cognito-drafts.js"]
